import {
  BadgeCheck,
  Bot,
  BrainCircuit,
  FileText,
  Image,
  LayoutTemplate,
  Mic2,
  PenTool,
  Sparkles,
  Video,
} from "lucide-react";
import type { CapabilityCategory, CreativeModel, LedgerItem, LibraryAsset, OrderRecord, Template, UserProfile } from "./types";

export const currentUser: UserProfile = {
  initials: "U",
  name: "管理员 U",
  email: "admin@tikpan.ai",
  role: "admin",
  tokens: 8.8,
  frozenTokens: 0,
  plan: "Growth 创作包",
  monthlyAllowance: 30,
};

export const capabilityTabs: Array<{ key: CapabilityCategory; label: string }> = [
  { key: "all", label: "全部" },
  { key: "chat", label: "聊天" },
  { key: "image", label: "图片" },
  { key: "video", label: "视频" },
  { key: "audio", label: "音频" },
  { key: "my", label: "我的" },
];

const imageControls: CreativeModel["controls"] = [
  {
    key: "prompt",
    label: "画面描述",
    type: "textarea",
    required: true,
    helper: "描述你想生成的画面、商品、场景或风格。",
  },
  {
    key: "size",
    label: "画面比例",
    type: "select",
    defaultValue: "auto",
    helper: "选择适合平台和素材用途的画面比例。",
    options: [
      { label: "自动", value: "auto" },
      { label: "方图 1:1", value: "1024x1024" },
      { label: "横图 3:2", value: "1536x1024" },
      { label: "竖图 2:3", value: "1024x1536" },
      { label: "横版封面", value: "3840x2160" },
    ],
  },
  {
    key: "quality",
    label: "清晰度",
    type: "segmented",
    defaultValue: "auto",
    options: [
      { label: "自动", value: "auto" },
      { label: "快速", value: "low" },
      { label: "标准", value: "medium" },
      { label: "精细", value: "high" },
    ],
  },
  {
    key: "n",
    label: "生成张数",
    type: "number",
    defaultValue: 1,
    min: 1,
    max: 10,
    step: 1,
  },
  {
    key: "background",
    label: "背景",
    type: "segmented",
    defaultValue: "opaque",
    helper: "当前能力建议使用不透明背景。",
    options: [
      { label: "自动", value: "auto" },
      { label: "不透明", value: "opaque" },
    ],
  },
  {
    key: "output_format",
    label: "输出格式",
    type: "segmented",
    defaultValue: "png",
    options: [
      { label: "PNG", value: "png" },
      { label: "JPEG", value: "jpeg" },
      { label: "WebP", value: "webp" },
    ],
  },
];

const textControls: CreativeModel["controls"] = [
  {
    key: "prompt",
    label: "创作需求",
    type: "textarea",
    required: true,
    helper: "描述目标、受众、语气和要输出的内容。",
  },
  {
    key: "tone",
    label: "语气",
    type: "segmented",
    defaultValue: "balanced",
    options: [
      { label: "自然", value: "balanced" },
      { label: "专业", value: "pro" },
      { label: "种草", value: "social" },
    ],
  },
  {
    key: "length",
    label: "篇幅",
    type: "segmented",
    defaultValue: "medium",
    options: [
      { label: "短", value: "short" },
      { label: "中", value: "medium" },
      { label: "长", value: "long" },
    ],
  },
];

const videoControls: CreativeModel["controls"] = [
  {
    key: "prompt",
    label: "视频描述",
    type: "textarea",
    required: true,
    helper: "描述镜头、节奏、产品动作和画面氛围。",
  },
  {
    key: "duration",
    label: "时长",
    type: "segmented",
    defaultValue: 5,
    options: [
      { label: "5 秒", value: 5 },
      { label: "8 秒", value: 8 },
      { label: "12 秒", value: 12 },
    ],
  },
  {
    key: "ratio",
    label: "比例",
    type: "segmented",
    defaultValue: "9:16",
    options: [
      { label: "9:16", value: "9:16" },
      { label: "16:9", value: "16:9" },
      { label: "1:1", value: "1:1" },
    ],
  },
];

export const creativeModels: CreativeModel[] = [
  {
    id: "claude-fable-creator",
    name: "Claude Fable 5",
    category: "chat",
    group: "大模型",
    provider: "创作对话",
    subtitle: "适合长文案、脚本和深度构思",
    description: "适合长内容构思、品牌故事、脚本拆解和复杂创作任务。",
    bestFor: ["长文案", "脚本", "创意策略"],
    tags: ["对话", "写作"],
    cost: 0.12,
    health: 100,
    favorite: true,
    controls: textControls,
    icon: Sparkles,
  },
  {
    id: "opus-creator",
    name: "Claude Opus 4.8",
    category: "chat",
    group: "大模型",
    provider: "创作对话",
    subtitle: "高难度创作和内容推理",
    description: "适合复杂内容策划、品牌定位、长链路营销和高质量改写。",
    bestFor: ["内容策略", "高质量改写", "深度策划"],
    tags: ["Pro", "对话"],
    cost: 0.3,
    health: 100,
    favorite: true,
    controls: textControls,
    icon: BrainCircuit,
  },
  {
    id: "gpt-creator",
    name: "GPT-5.5",
    category: "chat",
    group: "大模型",
    provider: "创作对话",
    subtitle: "通用写作与多轮创作",
    description: "适合标题、短文案、产品卖点、活动方案和日常创作。",
    bestFor: ["标题", "卖点", "方案"],
    tags: ["通用", "高效"],
    cost: 0.16,
    health: 100,
    controls: textControls,
    icon: Bot,
  },
  {
    id: "gemini-creator",
    name: "Gemini 3.1 Pro",
    category: "chat",
    group: "大模型",
    provider: "多模态创作",
    subtitle: "适合素材理解与内容整理",
    description: "适合分析商品资料、提炼卖点，并整理成可执行创作方案。",
    bestFor: ["资料整理", "卖点提炼", "内容结构"],
    tags: ["多模态", "分析"],
    cost: 0.14,
    health: 97,
    controls: textControls,
    icon: BadgeCheck,
  },
  {
    id: "deepseek-copy",
    name: "DeepSeek V4 Pro",
    category: "chat",
    group: "大模型",
    provider: "深度探索",
    subtitle: "适合结构化分析和脚本逻辑",
    description: "适合内容大纲、爆款拆解、脚本结构和逻辑增强。",
    bestFor: ["大纲", "拆解", "逻辑"],
    tags: ["分析", "脚本"],
    cost: 0.1,
    health: 100,
    controls: textControls,
    icon: FileText,
  },
  {
    id: "image-pro",
    name: "图像生成 Pro",
    category: "image",
    group: "图像创作",
    provider: "视觉生成",
    subtitle: "商品图、海报和封面",
    description: "适合商品图、广告海报和社媒封面，输入需求即可生成可继续编辑的视觉草稿。",
    bestFor: ["商品主图", "广告海报", "社媒封面"],
    tags: ["高清", "文生图"],
    cost: 0.18,
    health: 100,
    favorite: true,
    controls: imageControls,
    icon: Image,
  },
  {
    id: "product-photo",
    name: "商品图生成",
    category: "image",
    group: "图像创作",
    provider: "电商素材",
    subtitle: "白底图、场景图、卖点图",
    description: "适合电商上新，一次生成更贴近商品售卖场景的图片方向。",
    bestFor: ["白底主图", "场景图", "卖点图"],
    tags: ["电商", "主图"],
    cost: 0.22,
    health: 99,
    controls: imageControls,
    icon: Image,
  },
  {
    id: "video-story",
    name: "视频生成 Story",
    category: "video",
    group: "视频创作",
    provider: "短视频",
    subtitle: "产品展示和社媒短片",
    description: "适合把产品、场景和节奏描述转成短视频画面方案。",
    bestFor: ["产品展示", "社媒短片", "开场镜头"],
    tags: ["视频", "分镜"],
    cost: 1.5,
    health: 96,
    controls: videoControls,
    icon: Video,
  },
  {
    id: "short-video-script",
    name: "短视频分镜",
    category: "video",
    group: "视频创作",
    provider: "脚本分镜",
    subtitle: "镜头、字幕、节奏",
    description: "适合先生成短视频分镜脚本，再带入视频能力继续创作。",
    bestFor: ["镜头脚本", "口播", "字幕"],
    tags: ["脚本", "分镜"],
    cost: 0.24,
    health: 100,
    favorite: true,
    controls: videoControls,
    icon: PenTool,
  },
  {
    id: "viral-copy",
    name: "爆款文案助手",
    category: "chat",
    group: "文案创作",
    provider: "营销文案",
    subtitle: "小红书、广告和电商详情",
    description: "适合快速生成种草文案、卖点提炼、详情页和投放标题。",
    bestFor: ["小红书", "广告标题", "详情页"],
    tags: ["文案", "营销"],
    cost: 0.08,
    health: 100,
    controls: textControls,
    icon: PenTool,
  },
  {
    id: "audio-script",
    name: "音频脚本助手",
    category: "audio",
    group: "音频创作",
    provider: "口播脚本",
    subtitle: "旁白、口播、播客大纲",
    description: "适合生成口播稿、旁白结构和音频内容大纲。",
    bestFor: ["口播", "旁白", "播客"],
    tags: ["音频", "脚本"],
    cost: 0.08,
    health: 98,
    controls: textControls,
    icon: Mic2,
  },
];

export const featuredTemplates: Template[] = [
  {
    id: "new-product-set",
    title: "新品主图四件套",
    category: "今日精选",
    description: "主图、场景图、卖点图和封面一次带入工作台。",
    prompt: "为一款轻盈保湿精华生成新品主图四件套：白底主图、自然光场景图、核心卖点图、小红书封面。整体干净明亮，突出质地和高级感。",
    tokens: 0.72,
    accent: "teal",
  },
  {
    id: "product-poster",
    title: "新品广告海报",
    category: "热门模板",
    description: "适合活动预热、投放素材和品牌视觉方向。",
    prompt: "为一款轻盈保湿精华生成新品广告海报，画面干净明亮，产品居中，突出水润质感和高级品牌氛围。",
    tokens: 0.18,
    accent: "violet",
  },
  {
    id: "five-second-hook",
    title: "短视频开场 5 秒",
    category: "热门能力",
    description: "为产品短视频生成前三秒钩子和镜头节奏。",
    prompt: "为一款电商新品设计短视频开场 5 秒：包含镜头、画面、字幕、口播和节奏说明，目标是在前 3 秒抓住注意力。",
    tokens: 0.24,
    accent: "amber",
  },
  {
    id: "video-product-shot",
    title: "产品短视频画面",
    category: "视频创作",
    description: "后续接入视频能力后，可直接带入生成。",
    prompt: "为一款电商新品设计产品短视频画面：自然光、缓慢推进、突出瓶身质感和使用场景。",
    tokens: 1.5,
    accent: "sky",
  },
];

export const libraryAssets: LibraryAsset[] = [
  { id: "asset-1", title: "保湿精华主图方向 A", type: "图片", createdAt: "今天 14:20", model: "图像生成 Pro", favorite: true },
  { id: "asset-2", title: "夏季上新短视频画面", type: "视频", createdAt: "昨天 19:08", model: "视频生成 Story" },
  { id: "asset-3", title: "广告海报视觉方向", type: "图片", createdAt: "周三 10:35", model: "图像生成 Pro" },
  { id: "asset-4", title: "社媒封面视觉方向", type: "图片", createdAt: "周一 16:12", model: "图像生成 Pro" },
];

export const ledgerItems: LedgerItem[] = [
  { id: "ledger-1", title: "商品图生成", time: "今天 14:20", tokens: -0.22, status: "已完成" },
  { id: "ledger-2", title: "短视频分镜", time: "昨天 19:08", tokens: -0.12, status: "已完成" },
  { id: "ledger-3", title: "取消的海报任务", time: "昨天 18:44", tokens: 0.2, status: "已退回" },
  { id: "ledger-4", title: "月度额度发放", time: "本月 1 日", tokens: 30, status: "已完成" },
];

export const orders: OrderRecord[] = [
  { id: "TP20260704001", tokens: 30, status: "已完成", time: "2026-07-04 10:18" },
  { id: "TP20260628009", tokens: 10, status: "已完成", time: "2026-06-28 21:06" },
  { id: "TP20260621011", tokens: 30, status: "已取消", time: "2026-06-21 09:32" },
];

export const workflowHighlights = [
  { icon: Sparkles, title: "今日精选", copy: "新品主图、广告海报、社媒封面、产品短视频画面。" },
  { icon: LayoutTemplate, title: "热门模板", copy: "电商主图、社媒封面、广告海报、产品短视频。" },
  { icon: BadgeCheck, title: "更多创作能力", copy: "后续会继续补充视频创作、文案助手和电商工作流。" },
];
